# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(610, 418)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMaximumSize(QtCore.QSize(600, 671))
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMaximumSize(QtCore.QSize(600, 400))
        self.tabWidget.setObjectName("tabWidget")
        self.SVM = QtWidgets.QWidget()
        self.SVM.setObjectName("SVM")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.SVM)
        self.gridLayout_2.setContentsMargins(0, 5, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridGroupBox_2 = QtWidgets.QGroupBox(self.SVM)
        self.gridGroupBox_2.setObjectName("gridGroupBox_2")
        self.formLayout = QtWidgets.QFormLayout(self.gridGroupBox_2)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setContentsMargins(10, 5, 10, 5)
        self.formLayout.setHorizontalSpacing(50)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.gridGroupBox_2)
        font = QtGui.QFont()
        font.setFamily("Didot")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.kernel_val = QtWidgets.QComboBox(self.gridGroupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.kernel_val.sizePolicy().hasHeightForWidth())
        self.kernel_val.setSizePolicy(sizePolicy)
        self.kernel_val.setObjectName("kernel_val")
        self.kernel_val.addItem("")
        self.kernel_val.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.kernel_val)
        self.label_2 = QtWidgets.QLabel(self.gridGroupBox_2)
        font = QtGui.QFont()
        font.setFamily("Didot")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.gamma_val = QtWidgets.QComboBox(self.gridGroupBox_2)
        self.gamma_val.setFocusPolicy(QtCore.Qt.TabFocus)
        self.gamma_val.setObjectName("gamma_val")
        self.gamma_val.addItem("")
        self.gamma_val.addItem("")
        self.gamma_val.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.gamma_val)
        self.label_3 = QtWidgets.QLabel(self.gridGroupBox_2)
        font = QtGui.QFont()
        font.setFamily("Didot")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.C_val = QtWidgets.QDoubleSpinBox(self.gridGroupBox_2)
        self.C_val.setMinimum(0.01)
        self.C_val.setMaximum(10000.0)
        self.C_val.setProperty("value", 1.0)
        self.C_val.setObjectName("C_val")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.C_val)
        self.pre_btn1 = QtWidgets.QPushButton(self.gridGroupBox_2)
        self.pre_btn1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pre_btn1.setObjectName("pre_btn1")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.pre_btn1)
        self.svm_start = QtWidgets.QPushButton(self.gridGroupBox_2)
        self.svm_start.setObjectName("svm_start")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.svm_start)
        self.gamma_float = QtWidgets.QDoubleSpinBox(self.gridGroupBox_2)
        self.gamma_float.setEnabled(False)
        self.gamma_float.setObjectName("gamma_float")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.gamma_float)
        self.gridLayout.addWidget(self.gridGroupBox_2, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.SVM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.svm_results = QtWidgets.QListWidget(self.groupBox_2)
        self.svm_results.setObjectName("svm_results")
        self.gridLayout_5.addWidget(self.svm_results, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.SVM)
        self.groupBox.setMinimumSize(QtCore.QSize(350, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.svm_output = QtWidgets.QTextEdit(self.groupBox)
        self.svm_output.setReadOnly(True)
        self.svm_output.setObjectName("svm_output")
        self.gridLayout_3.addWidget(self.svm_output, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 2, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.SVM, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_9.setContentsMargins(0, 5, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridGroupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.gridGroupBox_3.setMaximumSize(QtCore.QSize(218, 16777215))
        self.gridGroupBox_3.setObjectName("gridGroupBox_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.gridGroupBox_3)
        self.formLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout_2.setContentsMargins(10, 5, 10, 0)
        self.formLayout_2.setHorizontalSpacing(20)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.gridGroupBox_3)
        font = QtGui.QFont()
        font.setFamily("Didot")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.base_esti_val = QtWidgets.QComboBox(self.gridGroupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.base_esti_val.setFont(font)
        self.base_esti_val.setObjectName("base_esti_val")
        self.base_esti_val.addItem("")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.base_esti_val)
        self.label_4 = QtWidgets.QLabel(self.gridGroupBox_3)
        font = QtGui.QFont()
        font.setFamily("Didot")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.n_esti_val = QtWidgets.QSpinBox(self.gridGroupBox_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.n_esti_val.setFont(font)
        self.n_esti_val.setMaximum(1000)
        self.n_esti_val.setProperty("value", 50)
        self.n_esti_val.setObjectName("n_esti_val")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.n_esti_val)
        self.label_6 = QtWidgets.QLabel(self.gridGroupBox_3)
        font = QtGui.QFont()
        font.setFamily("Didot")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.learning_rate_val = QtWidgets.QDoubleSpinBox(self.gridGroupBox_3)
        self.learning_rate_val.setMinimum(0.01)
        self.learning_rate_val.setMaximum(10000.0)
        self.learning_rate_val.setProperty("value", 1.0)
        self.learning_rate_val.setObjectName("learning_rate_val")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.learning_rate_val)
        self.pre_btn2 = QtWidgets.QPushButton(self.gridGroupBox_3)
        self.pre_btn2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pre_btn2.setObjectName("pre_btn2")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.pre_btn2)
        self.adaboost_start = QtWidgets.QPushButton(self.gridGroupBox_3)
        self.adaboost_start.setObjectName("adaboost_start")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.adaboost_start)
        self.gridLayout_6.addWidget(self.gridGroupBox_3, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.adaboost_results = QtWidgets.QListWidget(self.groupBox_3)
        self.adaboost_results.setObjectName("adaboost_results")
        self.gridLayout_7.addWidget(self.adaboost_results, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setMinimumSize(QtCore.QSize(350, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(350, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.adaboost_output = QtWidgets.QTextEdit(self.groupBox_4)
        self.adaboost_output.setObjectName("adaboost_output")
        self.gridLayout_8.addWidget(self.adaboost_output, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_4, 0, 1, 2, 1)
        self.gridLayout_9.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "算法的应用和评估窗口"))
        self.gridGroupBox_2.setTitle(_translate("Dialog", "参数设置"))
        self.label.setText(_translate("Dialog", "kernel:"))
        self.kernel_val.setItemText(0, _translate("Dialog", "linear"))
        self.kernel_val.setItemText(1, _translate("Dialog", "rbf"))
        self.label_2.setText(_translate("Dialog", "gamma:"))
        self.gamma_val.setCurrentText(_translate("Dialog", "auto"))
        self.gamma_val.setItemText(0, _translate("Dialog", "auto"))
        self.gamma_val.setItemText(1, _translate("Dialog", "scale"))
        self.gamma_val.setItemText(2, _translate("Dialog", "float"))
        self.label_3.setText(_translate("Dialog", "C:"))
        self.pre_btn1.setText(_translate("Dialog", "上一步"))
        self.svm_start.setText(_translate("Dialog", "开始"))
        self.groupBox_2.setTitle(_translate("Dialog", "结果"))
        self.groupBox.setTitle(_translate("Dialog", "输出"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.SVM), _translate("Dialog", "SVM"))
        self.gridGroupBox_3.setTitle(_translate("Dialog", "参数设置"))
        self.label_5.setText(_translate("Dialog", "base_estimator:"))
        self.base_esti_val.setItemText(0, _translate("Dialog", "DecisionTree"))
        self.label_4.setText(_translate("Dialog", "n_estimators:"))
        self.label_6.setText(_translate("Dialog", "learning_rate:"))
        self.pre_btn2.setText(_translate("Dialog", "上一步"))
        self.adaboost_start.setText(_translate("Dialog", "开始"))
        self.groupBox_3.setTitle(_translate("Dialog", "结果"))
        self.groupBox_4.setTitle(_translate("Dialog", "输出"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "AdaBoost"))

