# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '2nd_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.plotfig = QtWidgets.QWidget(self.widget)
        self.plotfig.setObjectName("plotfig")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.plotfig)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plot_layout = QtWidgets.QGridLayout()
        self.plot_layout.setObjectName("plot_layout")
        self.gridLayout_3.addLayout(self.plot_layout, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.plotfig)
        self.console = QtWidgets.QWidget(self.widget)
        self.console.setMinimumSize(QtCore.QSize(210, 0))
        self.console.setMaximumSize(QtCore.QSize(210, 16777215))
        self.console.setObjectName("console")
        self.gridLayout = QtWidgets.QGridLayout(self.console)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.console)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 196, 223))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setContentsMargins(12, 12, 12, 12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.dimesion_val = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.dimesion_val.setObjectName("dimesion_val")
        self.gridLayout_2.addWidget(self.dimesion_val, 2, 1, 1, 1)
        self.class_val = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.class_val.setObjectName("class_val")
        self.gridLayout_2.addWidget(self.class_val, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.sample_val = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.sample_val.setObjectName("sample_val")
        self.gridLayout_2.addWidget(self.sample_val, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 3, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 2)
        self.impute_chk = QtWidgets.QCheckBox(self.console)
        self.impute_chk.setEnabled(True)
        self.impute_chk.setObjectName("impute_chk")
        self.gridLayout.addWidget(self.impute_chk, 2, 0, 1, 1)
        self.reset = QtWidgets.QPushButton(self.console)
        self.reset.setObjectName("reset")
        self.gridLayout.addWidget(self.reset, 5, 0, 1, 1)
        self.next = QtWidgets.QPushButton(self.console)
        self.next.setObjectName("next")
        self.gridLayout.addWidget(self.next, 5, 1, 1, 1)
        self.std_chk = QtWidgets.QCheckBox(self.console)
        self.std_chk.setObjectName("std_chk")
        self.gridLayout.addWidget(self.std_chk, 1, 0, 1, 1)
        self.horizontalLayout.addWidget(self.console)
        self.horizontalLayout_2.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 30))
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "数据预处理窗口"))
        self.label_2.setText(_translate("MainWindow", "Samples per class:"))
        self.dimesion_val.setText(_translate("MainWindow", "2"))
        self.class_val.setText(_translate("MainWindow", "2"))
        self.label.setText(_translate("MainWindow", "Classes:"))
        self.label_3.setText(_translate("MainWindow", "Dimensionality："))
        self.sample_val.setText(_translate("MainWindow", "50, 50"))
        self.impute_chk.setText(_translate("MainWindow", "缺失值处理"))
        self.reset.setText(_translate("MainWindow", "重置"))
        self.next.setText(_translate("MainWindow", "下一步"))
        self.std_chk.setText(_translate("MainWindow", "标准化"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

